Created moon project for diff-generator in tools directory
adobe/spectrum-tokens pull request #344
Opened 2024-05-31 18:45 UTC by shirlsli

## Description

This commit contains the setup of the diff generating tool using the node-tool template.

## Related Issue

This project intends to improve diff generation between two schemas.

## Motivation and Context

The motivation behind this project is to improve the diff generation between two schemas. Currently, the diff generation is inaccurate. For example, schema values that aren't deleted get marked as deleted.

## How Has This Been Tested?

The project hasn't been tested yet, because this PR only contains the project setup.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-31 18:48 UTC, GarthDB commented
<!-- moon-run-report: unknown -->

## Run report for [906a8704](https://github.com/adobe/spectrum-tokens/commit/906a87048c864139df8158ec30188c68df08fb4a)
Total time: 45.6s | Comparison time: 47.8s | Estimated savings: 2.3s (4.8% faster)
|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `SyncWorkspace` | 0ms | Passed |  |
| ⬛️ | `SetupNodeTool(~20.12)` | 1.3s | Skipped |  |
| 🟩 | `InstallNodeDeps(~20.12)` | 6.5s | Passed |  |
| 🟩 | `SyncNodeProject(diff)` | 0.2ms | Passed |  |
| 🟩 | `SyncNodeProject(visualizer)` | 0.2ms | Passed |  |
| 🟩 | `SyncNodeProject(root)` | 0.4ms | Passed |  |
| 🟩 | `RunTask(diff:diff)` | 97.2ms | Passed |  |
| 🟩 | `RunTask(diff:test)` | 1.3s | Passed |  |
| 🟩 | `RunTask(visualizer:typescript)` | 2.4s | Passed |  |
| 🟩 | `RunTask(root:test)` | 1.6s | Passed |  |
| 🟩 | `RunTask(visualizer:build)` | 1.7s | Passed |  |
| 🟩 | `SyncNodeProject(tokens)` | 0.4ms | Passed |  |
| 🟩 | `SyncNodeProject(site)` | 0.3ms | Passed |  |
| 🟩 | `RunTask(tokens:buildTokens)` | 15.3s | Passed |  |
| 🟩 | `RunTask(tokens:buildManifest)` | 263.4ms | Passed |  |
| 🟩 | `RunTask(site:copySchema)` | 69ms | Passed |  |
| 🟩 | `RunTask(site:clean)` | 181.1ms | Passed |  |
| 🟩 | `RunTask(tokens:build)` | 0.1ms | Passed |  |
| 🟩 | `RunTask(tokens:generateDiffResult)` | 1.8s | Passed |  |
| 🟩 | `RunTask(tokens:test)` | 3.9s | Passed |  |
| | And 5 more... | | | |

<details><summary><strong>Expanded report</strong></summary><div>

|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `RunTask(site:build)` | 17.6s | Passed |  |
| 🟩 | `SyncNodeProject(csvGenerator)` | 0.3ms | Passed |  |
| 🟩 | `RunTask(site:export)` | 0.1ms | Passed |  |
| 🟩 | `RunTask(csvGenerator:generateCSV)` | 158.8ms | Passed |  |
| 🟩 | `RunTask(csvGenerator:test)` | 887.8ms | Passed |  |

</div></details>

<details><summary><strong>Touched files</strong></summary><div>

```
.moon/workspace.yml
pnpm-lock.yaml
tools/diff-generator/README.md
tools/diff-generator/moon.yml
tools/diff-generator/package.json
tools/diff-generator/src/index.js
tools/diff-generator/test/index.test.js
```

</div></details>

2024-05-31 22:53 UTC, GarthDB commented
![Bravest Warriors Applause](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnV3MTlvajE3d3lrZ2pzdTlnOXdiZXlnb2N4cHFlbmVkNmJxaTc3ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kiblLDUFurYI0/giphy.gif)

2024-06-03 19:03 UTC, GarthDB commented on tools/diff-generator/test/test-schemas/entire-schema-renamed.json
> +    "component": "opacity-checkerboard",
Could you add a uuid to the base of the set tokens?

2024-06-03 20:09 UTC, shirlsli commented on tools/diff-generator/test/test-schemas/entire-schema-renamed.json
> +    "component": "opacity-checkerboard",
Yes! I just pushed a commit with the added uuid.

2024-07-09 17:26 UTC, GarthDB requested changes
Could you also update the root README.md file to include the diff generator in the list of packages in the mono repo? https://github.com/adobe/spectrum-tokens/blob/main/README.md?plain=1#L18

2024-07-09 17:26 UTC, GarthDB commented on tools/diff-generator/package.json
> +  "private": true,
If `"private": true` is in this file it won't publish this package to npm. Could you just delete it?

2024-07-09 17:26 UTC, GarthDB commented on tools/diff-generator/moon.yml
> +    platform: node
Could you add a task for code coverage? It's in the package.json file, but it's ok to have it here too so it can be run in github actions for as part of `moon ci`

2024-07-09 17:26 UTC, GarthDB commented on tools/diff-generator/package.json
> +  "name": "diff-generator",
We should update this name to include the `@adobe` org namespace. What do you think of `@adobe/token-diff-generator`? Or `@adobe/token-diff`?

2024-07-09 17:28 UTC, GarthDB requested changes

2024-07-09 17:28 UTC, GarthDB commented on .changeset/small-radios-mate.md
> +"diff-generator": major
We will need to update this to the new package name in `tools/diff-generator/package.json`.

2024-07-09 17:35 UTC, GarthDB requested changes

2024-07-09 17:35 UTC, GarthDB commented on tools/diff-generator/README.md
> +pnpm i @adobe/spectrum-tokens/token-diff-generator
This would just be the `name` in the `tools/diff-generator/package.json` file. So, `pnpm I @adobe/token-diff-generator`. NPM doesn't support sub packages like this.

2024-07-09 17:35 UTC, GarthDB commented on tools/diff-generator/README.md
> +import tokenDiff from “@adobe/spectrum-tokens/token-diff-generator”;
Similar to the comment above, this would just be the name property in the package.json file.

2024-07-09 17:35 UTC, GarthDB commented on tools/diff-generator/README.md
> +import tokenDiff from “@adobe/spectrum-tokens/token-diff-generator”;
Same thing here for the package name.

2024-07-09 17:35 UTC, GarthDB commented on tools/diff-generator/README.md
> +import fileImport from “@adobe/spectrum-tokens/token-diff-generator”;
and here.

2024-08-07 22:51 UTC, GarthDB approved these changes

2024-08-07 22:52 UTC, merged