chore: refactor component-schemas into package
adobe/spectrum-tokens pull request #353
Opened 2024-06-07 14:30 UTC by karstens

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-07 14:33 UTC, karstens commented on packages/tokens/test/schemaValidator.test.js
> -/*
@GarthDB I deleted this file, because it was a duplicate of `[componentSchemaValidator.test.js]`. All token-types schemas are tested by `tokenSchemaValidator.test.js` and `componentSchemaValidator.test.js` is moved to `packages/component-schemas/test`

2024-06-13 15:27 UTC, GarthDB commented
<!-- moon-run-report: unknown -->

## Run report for [5946a63c](https://github.com/adobe/spectrum-tokens/commit/5946a63ce1036acb8f52cf9a53744c2ec858f60c)
Total time: 45s | Comparison time: 49s | Estimated savings: 4s (8.1% faster)
|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `SyncWorkspace` | 0ms | Passed |  |
| ⬛️ | `SetupNodeTool(~20.12)` | 1.2s | Skipped |  |
| 🟩 | `InstallNodeDeps(~20.12)` | 6.8s | Passed |  |
| 🟩 | `SyncNodeProject(componentSchemas)` | 0.2ms | Passed |  |
| 🟩 | `SyncNodeProject(visualizer)` | 0.3ms | Passed |  |
| 🟩 | `SyncNodeProject(root)` | 0.2ms | Passed |  |
| 🟩 | `SyncNodeProject(tokens)` | 1.4ms | Passed |  |
| 🟩 | `RunTask(componentSchemas:make)` | 28.3ms | Passed |  |
| 🟩 | `RunTask(componentSchemas:buildSchemas)` | 39ms | Passed |  |
| 🟩 | `RunTask(componentSchemas:clean)` | 27.4ms | Passed |  |
| 🟩 | `RunTask(componentSchemas:build)` | 31.4ms | Passed |  |
| 🟩 | `RunTask(componentSchemas:test)` | 1.9s | Passed |  |
| 🟩 | `RunTask(visualizer:typescript)` | 2.4s | Passed |  |
| 🟩 | `RunTask(root:test)` | 1.6s | Passed |  |
| 🟩 | `RunTask(visualizer:build)` | 2.1s | Passed |  |
| 🟩 | `RunTask(tokens:buildTokens)` | 16.1s | Passed |  |
| 🟩 | `RunTask(tokens:buildManifest)` | 265.5ms | Passed |  |
| 🟩 | `SyncNodeProject(site)` | 0.7ms | Passed |  |
| 🟩 | `RunTask(site:copyComponentSchema)` | 34ms | Passed |  |
| 🟩 | `RunTask(site:copyTokenTypeSchema)` | 43ms | Passed |  |
| | And 9 more... | | | |

<details><summary><strong>Expanded report</strong></summary><div>

|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `RunTask(site:clean)` | 116.3ms | Passed |  |
| 🟩 | `SyncNodeProject(csvGenerator)` | 1.3ms | Passed |  |
| 🟩 | `RunTask(tokens:build)` | 14ms | Passed |  |
| 🟩 | `RunTask(tokens:generateDiffResult)` | 1.6s | Passed |  |
| 🟩 | `RunTask(tokens:test)` | 3.2s | Passed |  |
| 🟩 | `RunTask(site:build)` | 17.4s | Passed |  |
| 🟩 | `RunTask(site:export)` | 149.2ms | Passed |  |
| 🟩 | `RunTask(csvGenerator:generateCSV)` | 176.3ms | Passed |  |
| 🟩 | `RunTask(csvGenerator:test)` | 934.2ms | Passed |  |

</div></details>

<details><summary><strong>Touched files</strong></summary><div>

```
.moon/workspace.yml
docs/site/lib/components.js
docs/site/moon.yml
docs/site/public/schemas/token-types/color-set.json
docs/site/public/schemas/token-types/scale-set.json
packages/component-schemas/index.js
packages/component-schemas/moon.yml
packages/component-schemas/package.json
packages/component-schemas/schemas/component.json
packages/component-schemas/schemas/components/action-bar.json
packages/component-schemas/schemas/components/action-button.json
packages/component-schemas/schemas/components/action-group.json
packages/component-schemas/schemas/components/alert-banner.json
packages/component-schemas/schemas/components/alert-dialog.json
packages/component-schemas/schemas/components/avatar.json
packages/component-schemas/schemas/components/badge.json
packages/component-schemas/schemas/components/body.json
packages/component-schemas/schemas/components/bottom-navigation-android.json
packages/component-schemas/schemas/components/breadcrumbs.json
packages/component-schemas/schemas/components/button-group.json
packages/component-schemas/schemas/components/button.json
packages/component-schemas/schemas/components/checkbox-group.json
packages/component-schemas/schemas/components/checkbox.json
packages/component-schemas/schemas/components/close-button.json
packages/component-schemas/schemas/components/code.json
packages/component-schemas/schemas/components/color-area.json
packages/component-schemas/schemas/components/color-loupe.json
packages/component-schemas/schemas/components/color-slider.json
packages/component-schemas/schemas/components/color-wheel.json
packages/component-schemas/schemas/components/combo-box.json
packages/component-schemas/schemas/components/contextual-help.json
packages/component-schemas/schemas/components/detail.json
packages/component-schemas/schemas/components/divider.json
packages/component-schemas/schemas/components/field-label.json
packages/component-schemas/schemas/components/heading.json
packages/component-schemas/schemas/components/help-text.json
packages/component-schemas/schemas/components/in-line-alert.json
packages/component-schemas/schemas/components/link.json
packages/component-schemas/schemas/components/menu.json
packages/component-schemas/schemas/components/meter.json
packages/component-schemas/schemas/components/picker.json
packages/component-schemas/schemas/components/popover.json
packages/component-schemas/schemas/components/progress-bar.json
packages/component-schemas/schemas/components/progress-circle.json
packages/component-schemas/schemas/components/radio-group.json
packages/component-schemas/schemas/components/rating.json
packages/component-schemas/schemas/components/scroll-zoom-bar.json
packages/component-schemas/schemas/components/side-navigation.json
packages/component-schemas/schemas/components/slider.json
packages/component-schemas/schemas/components/status-light.json
packages/component-schemas/schemas/components/swatch-group.json
packages/component-schemas/schemas/components/swatch.json
packages/component-schemas/schemas/components/switch.json
packages/component-schemas/schemas/components/tab-bar-ios.json
packages/component-schemas/schemas/components/tabs.json
packages/component-schemas/schemas/components/tag.json
packages/component-schemas/schemas/components/text-area.json
packages/component-schemas/schemas/components/text-field.json
packages/component-schemas/schemas/components/toast.json
packages/component-schemas/schemas/components/tooltip.json
packages/component-schemas/schemas/components/tray.json
packages/component-schemas/schemas/components/tree-view.json
packages/component-schemas/schemas/types/component-size.json
packages/component-schemas/schemas/types/hex-color.json
packages/component-schemas/schemas/types/typography-classification.json
packages/component-schemas/schemas/types/typography-script.json
packages/component-schemas/schemas/types/workflow-icon.json
packages/component-schemas/test/componentSchemaValidator.test.js
packages/tokens/schemas/component.json
packages/tokens/schemas/components/action-bar.json
packages/tokens/schemas/components/action-button.json
packages/tokens/schemas/components/action-group.json
packages/tokens/schemas/components/alert-banner.json
packages/tokens/schemas/components/alert-dialog.json
packages/tokens/schemas/components/avatar.json
packages/tokens/schemas/components/badge.json
packages/tokens/schemas/components/body.json
packages/tokens/schemas/components/bottom-navigation-android.json
packages/tokens/schemas/components/breadcrumbs.json
packages/tokens/schemas/components/button-group.json
packages/tokens/schemas/components/button.json
packages/tokens/schemas/components/checkbox-group.json
packages/tokens/schemas/components/checkbox.json
packages/tokens/schemas/components/close-button.json
packages/tokens/schemas/components/code.json
packages/tokens/schemas/components/color-area.json
packages/tokens/schemas/components/color-loupe.json
packages/tokens/schemas/components/color-slider.json
packages/tokens/schemas/components/color-wheel.json
packages/tokens/schemas/components/combo-box.json
packages/tokens/schemas/components/contextual-help.json
packages/tokens/schemas/components/detail.json
packages/tokens/schemas/components/divider.json
packages/tokens/schemas/components/field-label.json
packages/tokens/schemas/components/heading.json
packages/tokens/schemas/components/help-text.json
packages/tokens/schemas/components/in-line-alert.json
packages/tokens/schemas/components/link.json
packages/tokens/schemas/components/menu.json
packages/tokens/schemas/components/meter.json
packages/tokens/schemas/components/picker.json
packages/tokens/schemas/components/popover.json
packages/tokens/schemas/components/progress-bar.json
packages/tokens/schemas/components/progress-circle.js [...]

2024-06-13 15:54 UTC, GarthDB requested changes
I made a couple of changes to fix the tests in order to make a snapshot release.

2024-06-13 15:54 UTC, GarthDB commented on packages/component-schemas/moon.yml
> +    command:
I don't think we need a dist. It isn't any different from the source directory.

2024-06-13 15:55 UTC, GarthDB requested changes

2024-06-13 15:59 UTC, GarthDB requested changes

2024-06-13 15:59 UTC, GarthDB commented on packages/component-schemas/index.js
We need to add tests for these functions.

2024-06-13 21:11 UTC, jianliao commented on packages/component-schemas/index.js
> +  await readJson(resolve(__dirname, "src", schemaFileName));
The released package does not have `src` folder.

2024-06-13 21:11 UTC, jianliao commented on packages/component-schemas/index.js
> +  return await Promise.all(schemaFileNames.map(getFileTokens)).then(
`getFileTokens` function is undefined.

2024-06-18 10:04 UTC, karstens commented on packages/component-schemas/moon.yml
> +    command:
@GarthDB I was assuming, that we don't want people access the "source" schemas directly, since this is an issue in the tokens package. I did consider the schemas (with the "getAll" helper in the index.js) and thought a dist folder could be helpful, in case we want to change the structure or add more es modules support or things like that.

2024-06-18 13:21 UTC, karstens commented on packages/component-schemas/index.js
> +  await readJson(resolve(__dirname, "src", schemaFileName));
@GarthDB @jianliao I wonder, how this function does work? There is no "src" folder, but all tests are passing?!

2024-08-20 14:33 UTC, karstens commented
@GarthDB test fail because of the new tab-item-json schema. How can I fix it? See https://github.com/adobe/spectrum-tokens/pull/353/commits/672d2d0a1dec70c0fc8c8a0b4be4d583ff312ac1

2025-06-19 21:22 UTC, GarthDB approved these changes

2025-06-19 21:26 UTC, merged